# Đọc dữ liệu từ thư mục 2023
Tiến hành đọc tất cả các tệp `.xlsx` trong thư mục `2023/` bằng thư viện `pandas`.

In [2]:
import pandas as pd
import glob
import os

# Đường dẫn đến thư mục 2023 (từ thư mục EDA/)
folder_path = os.path.join('..', '2023')

# Đọc từng file vào các biến riêng biệt
df_cu_jut = pd.read_excel(os.path.join(folder_path, 'Huyện Cư Jút.xlsx'))
df_krong_no = pd.read_excel(os.path.join(folder_path, 'Huyện Krông Nô.xlsx'))
df_tuy_duc = pd.read_excel(os.path.join(folder_path, 'Huyện Tuy Đức.xlsx'))
df_dak_glong = pd.read_excel(os.path.join(folder_path, 'Huyện Đăk Glong.xlsx'))
df_dak_mil = pd.read_excel(os.path.join(folder_path, 'Huyện Đắk Mil.xlsx'))
df_dak_rlap = pd.read_excel(os.path.join(folder_path, 'Huyện Đắk RLấp.xlsx'))
df_dak_song = pd.read_excel(os.path.join(folder_path, 'Huyện Đắk Song.xlsx'))
df_gia_nghia = pd.read_excel(os.path.join(folder_path, 'Thành phố Gia Nghĩa.xlsx'))

# Kiểm tra thử dữ liệu của một huyện
print("Dữ liệu Huyện Cư Jút:")
print(df_cu_jut.head())

Dữ liệu Huyện Cư Jút:
                date   family.hostName family.code family.coDanTocTaiCho  \
0  Thời gian rà soát            Chủ hộ       Mã hộ       Dân tộc tại chỗ
1                NaN        Y PÔL KNUL          61                   NaN
2                NaN  PHÙNG THỊ ÁNH           1                   NaN
3                NaN       HỨA PI ÁI           2                   NaN
4                NaN      LÀNH THỊ LAN           3                   NaN

  family.hostGender family.numberOfMembers quickReview.result   b1Point  \
0         Giới tính           Số nhân khẩu            Phiếu A  Phiếu B1
1               Nam                      4                 --       NaN
2                Nữ                      2                 --       NaN
3               Nam                      6                 --       NaN
4                Nữ                      4                 --       NaN

    b2Point         classify       reviewer
0  Phiếu B2  Kết quả rà soát  Người rà soát
1       NaN         Hộ nghèo            NaN
2       NaN         Hộ nghèo            NaN
3       NaN         Hộ nghèo            NaN
4       NaN         Hộ nghèo            NaN

In [3]:
df_cu_jut.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2103 entries, 0 to 2102
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   date                    1 non-null      object
 1   family.hostName         2103 non-null   object
 2   family.code             2103 non-null   object
 3   family.coDanTocTaiCho   412 non-null    object
 4   family.hostGender       2101 non-null   object
 5   family.numberOfMembers  2103 non-null   object
 6   quickReview.result      2103 non-null   object
 7   b1Point                 1 non-null      object
 8   b2Point                 1 non-null      object
 9   classify                2103 non-null   object
 10  reviewer                1 non-null      object
dtypes: object(11)
memory usage: 180.9+ KB

In [ ]:
# Lọc các dòng có 'family.code' và 'family.hostName' bị lặp trong df_cu_jut
duplicates = df_cu_jut[df_cu_jut.duplicated(subset=['family.code', 'family.hostName'], keep=False)]

print(f"Số lượng dòng trùng lặp (Mã hộ & Tên chủ hộ): {len(duplicates)}")
duplicates.sort_values(by=['family.code', 'family.hostName'])

Số lượng dòng có mã hộ trùng lặp: 2038

,date,family.hostName,family.code,family.coDanTocTaiCho,family.hostGender,family.numberOfMembers,quickReview.result,b1Point,b2Point,classify,reviewer
369,NaN,LƯƠNG VĂN PHONG,1,NaN,Nam,5,--,NaN,NaN,Hộ nghèo,NaN
134,NaN,LỤC VĂN CƯỜNG,1,NaN,Nam,5,--,NaN,NaN,Hộ nghèo,NaN
175,NaN,HOÀNG THỊ TIỆM,1,NaN,Nữ,6,--,NaN,NaN,Hộ nghèo,NaN
236,NaN,ĐỒNG XUÂN BỐN,1,NaN,Nam,3,--,NaN,NaN,Hộ nghèo,NaN
1078,NaN,NGUYỄN THỊ CHIẾN,1,NaN,Nữ,2,--,NaN,NaN,Hộ cận nghèo,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2021,NaN,BÀN VĂN PHÂU,99,NaN,Nam,4,--,NaN,NaN,Hộ nghèo,NaN
117,NaN,BÀN VĂN PHÂU,99,NaN,Nam,4,--,NaN,NaN,Hộ nghèo,NaN
703,NaN,H JUN KBUÔR,99,Có,Nữ,4,--,NaN,NaN,Hộ nghèo,NaN
950,NaN,NGUYỄN VĂN HOÀN,99,NaN,Nữ,2,--,NaN,NaN,Hộ cận nghèo,NaN
1874,NaN,H JUN KBUÔR,99,Có,Nữ,4,--,NaN,NaN,Hộ nghèo,NaN

In [5]:
# Hiển thị các dòng có 'family.hostGender' là null trong df_cu_jut
null_gender = df_cu_jut[df_cu_jut['family.hostGender'].isna()]

print(f"Số lượng dòng có giới tính chủ hộ bị thiếu: {len(null_gender)}")
null_gender.head(20) # Hiển thị 20 dòng đầu tiên bị thiếu

Số lượng dòng có giới tính chủ hộ bị thiếu: 2

,date,family.hostName,family.code,family.coDanTocTaiCho,family.hostGender,family.numberOfMembers,quickReview.result,b1Point,b2Point,classify,reviewer
734,NaN,Y ĐAWIT PRIÊNG,66,Có,NaN,4,--,NaN,NaN,Hộ nghèo,NaN
1841,NaN,Y ĐAWIT PRIÊNG,66,Có,NaN,4,--,NaN,NaN,Hộ nghèo,NaN

## Kiểm tra dữ liệu các huyện còn lại
Tiến hành kiểm tra trùng lặp mã hộ (`family.code`) và thiếu thông tin giới tính (`family.hostGender`) cho các huyện khác.

In [ ]:
# Huyện Krông Nô
print(f"--- Huyện Krông Nô ---")
dup_krong_no = df_krong_no[df_krong_no.duplicated(subset=['family.code', 'family.hostName'], keep=False)]
null_gen_krong_no = df_krong_no[df_krong_no['family.hostGender'].isna()]

print(f"Số lượng trùng (Mã hộ & Tên chủ hộ): {len(dup_krong_no)}")
print(f"Số lượng thiếu giới tính: {len(null_gen_krong_no)}")
if len(null_gen_krong_no) > 0:
    display(null_gen_krong_no)

--- Huyện Krông Nô ---
Số lượng trùng mã hộ: 2987
Số lượng thiếu giới tính: 387

,date,family.hostName,family.code,family.coDanTocTaiCho,family.hostGender,family.numberOfMembers,quickReview.result,b1Point,b2Point,classify,reviewer
255,NaN,Y Nhũ KPơr,402,NaN,NaN,5,--,NaN,NaN,Hộ cận nghèo,NaN
256,NaN,Y Ká Bu Tông,401,NaN,NaN,4,--,NaN,NaN,Hộ cận nghèo,NaN
257,NaN,Y Xuân,400,NaN,NaN,4,--,NaN,NaN,Hộ cận nghèo,NaN
258,NaN,Y Khai,399,NaN,NaN,4,--,NaN,NaN,Hộ cận nghèo,NaN
259,NaN,Phùng Văn Đồng,398,NaN,NaN,3,--,NaN,NaN,Hộ cận nghèo,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2991,NaN,Y Đuế,308,NaN,NaN,4,--,NaN,NaN,Hộ cận nghèo,NaN
2992,NaN,Cầm Thị Long,314,NaN,NaN,2,--,NaN,NaN,Hộ cận nghèo,NaN
2993,NaN,Trần Văn Hưng,317,NaN,NaN,4,--,NaN,NaN,Hộ cận nghèo,NaN
2994,NaN,H Drăng,324,NaN,NaN,4,--,NaN,NaN,Hộ cận nghèo,NaN
2995,NaN,Y Du ÊCăm,333,NaN,NaN,7,--,NaN,NaN,Hộ cận nghèo,NaN

In [ ]:
# Huyện Tuy Đức
print(f"--- Huyện Tuy Đức ---")
dup_tuy_duc = df_tuy_duc[df_tuy_duc.duplicated(subset=['family.code', 'family.hostName'], keep=False)]
null_gen_tuy_duc = df_tuy_duc[df_tuy_duc['family.hostGender'].isna()]

print(f"Số lượng trùng (Mã hộ & Tên chủ hộ): {len(dup_tuy_duc)}")
print(f"Số lượng thiếu giới tính: {len(null_gen_tuy_duc)}")
if len(null_gen_tuy_duc) > 0:
    display(null_gen_tuy_duc)

--- Huyện Tuy Đức ---
Số lượng trùng mã hộ: 5066
Số lượng thiếu giới tính: 1

,date,family.hostName,family.code,family.coDanTocTaiCho,family.hostGender,family.numberOfMembers,quickReview.result,b1Point,b2Point,classify,reviewer
979,NaN,SÙNG A TRÁNG,145,NaN,NaN,4,--,NaN,NaN,Hộ cận nghèo,NaN

In [ ]:
# Huyện Đăk Glong
print(f"--- Huyện Đăk Glong ---")
dup_dak_glong = df_dak_glong[df_dak_glong.duplicated(subset=['family.code', 'family.hostName'], keep=False)]
null_gen_dak_glong = df_dak_glong[df_dak_glong['family.hostGender'].isna()]

print(f"Số lượng trùng (Mã hộ & Tên chủ hộ): {len(dup_dak_glong)}")
print(f"Số lượng thiếu giới tính: {len(null_gen_dak_glong)}")
if len(null_gen_dak_glong) > 0:
    display(null_gen_dak_glong)

--- Huyện Đăk Glong ---
Số lượng trùng mã hộ: 4555
Số lượng thiếu giới tính: 132

,date,family.hostName,family.code,family.coDanTocTaiCho,family.hostGender,family.numberOfMembers,quickReview.result,b1Point,b2Point,classify,reviewer
1954,NaN,Hạng A Nhà,193,NaN,NaN,7,--,NaN,NaN,Hộ nghèo,NaN
1955,NaN,Sùng Seo Súa,192,NaN,NaN,5,--,NaN,NaN,Hộ nghèo,NaN
1956,NaN,Vàng A Chứ,191,NaN,NaN,9,--,NaN,NaN,Hộ nghèo,NaN
1957,NaN,Giàng Seo Phổng,190,NaN,NaN,5,--,NaN,NaN,Hộ nghèo,NaN
1958,NaN,Vàng A Dình,189,NaN,NaN,9,--,NaN,NaN,Hộ nghèo,NaN
...,...,...,...,...,...,...,...,...,...,...,...
3873,NaN,Giàng Thị Nhìa,175,NaN,NaN,7,--,NaN,NaN,Hộ nghèo,NaN
3874,NaN,Vàng A Chứ,191,NaN,NaN,9,--,NaN,NaN,Hộ nghèo,NaN
3985,NaN,Lê Văn Hải,69,NaN,NaN,6,--,NaN,NaN,Hộ nghèo,NaN
3986,NaN,K' Thương,76,NaN,NaN,4,--,NaN,NaN,Hộ nghèo,NaN
3987,NaN,Nguyễn Văn Xá,82,NaN,NaN,6,--,NaN,NaN,Hộ nghèo,NaN

In [ ]:
# Huyện Đắk Mil
print(f"--- Huyện Đắk Mil ---")
dup_dak_mil = df_dak_mil[df_dak_mil.duplicated(subset=['family.code', 'family.hostName'], keep=False)]
null_gen_dak_mil = df_dak_mil[df_dak_mil['family.hostGender'].isna()]

print(f"Số lượng trùng (Mã hộ & Tên chủ hộ): {len(dup_dak_mil)}")
print(f"Số lượng thiếu giới tính: {len(null_gen_dak_mil)}")
if len(null_gen_dak_mil) > 0:
    display(null_gen_dak_mil)

--- Huyện Đắk Mil ---
Số lượng trùng mã hộ: 1412
Số lượng thiếu giới tính: 0

In [ ]:
# Huyện Đắk RLấp
print(f"--- Huyện Đắk RLấp ---")
dup_dak_rlap = df_dak_rlap[df_dak_rlap.duplicated(subset=['family.code', 'family.hostName'], keep=False)]
null_gen_dak_rlap = df_dak_rlap[df_dak_rlap['family.hostGender'].isna()]

print(f"Số lượng trùng (Mã hộ & Tên chủ hộ): {len(dup_dak_rlap)}")
print(f"Số lượng thiếu giới tính: {len(null_gen_dak_rlap)}")
if len(null_gen_dak_rlap) > 0:
    display(null_gen_dak_rlap)

--- Huyện Đắk RLấp ---
Số lượng trùng mã hộ: 1170
Số lượng thiếu giới tính: 0

In [ ]:
# Huyện Đắk Song
print(f"--- Huyện Đắk Song ---")
dup_dak_song = df_dak_song[df_dak_song.duplicated(subset=['family.code', 'family.hostName'], keep=False)]
null_gen_dak_song = df_dak_song[df_dak_song['family.hostGender'].isna()]

print(f"Số lượng trùng (Mã hộ & Tên chủ hộ): {len(dup_dak_song)}")
print(f"Số lượng thiếu giới tính: {len(null_gen_dak_song)}")
if len(null_gen_dak_song) > 0:
    display(null_gen_dak_song)

--- Huyện Đắk Song ---
Số lượng trùng mã hộ: 1807
Số lượng thiếu giới tính: 89

,date,family.hostName,family.code,family.coDanTocTaiCho,family.hostGender,family.numberOfMembers,quickReview.result,b1Point,b2Point,classify,reviewer
611,NaN,Phan Văn Hoàn,53,NaN,NaN,4,--,NaN,NaN,Hộ cận nghèo,NaN
709,NaN,Bùi Đình Sơn,51,NaN,NaN,6,--,NaN,NaN,Hộ cận nghèo,NaN
710,NaN,Bùi Bình Giang,59,NaN,NaN,4,--,NaN,NaN,Hộ cận nghèo,NaN
712,NaN,Đàm Duy Tùng,75,NaN,NaN,2,--,NaN,NaN,Hộ cận nghèo,NaN
713,NaN,Trần Hữu Cường,84,NaN,NaN,4,--,NaN,NaN,Hộ cận nghèo,NaN
...,...,...,...,...,...,...,...,...,...,...,...
1708,NaN,Trương Văn Cảnh,163,NaN,NaN,4,--,NaN,NaN,Hộ cận nghèo,NaN
1709,NaN,Nguyễn Văn Quang,164,NaN,NaN,5,--,NaN,NaN,Hộ cận nghèo,NaN
1710,NaN,Đặng Công Cường,165,NaN,NaN,6,--,NaN,NaN,Hộ cận nghèo,NaN
1711,NaN,Nguyễn Định Quốc,167,NaN,NaN,4,--,NaN,NaN,Hộ cận nghèo,NaN
1712,NaN,Phạm Văn Vinh,173,NaN,NaN,5,--,NaN,NaN,Hộ cận nghèo,NaN

In [ ]:
# Thành phố Gia Nghĩa
print(f"--- Thành phố Gia Nghĩa ---")
dup_gia_nghia = df_gia_nghia[df_gia_nghia.duplicated(subset=['family.code', 'family.hostName'], keep=False)]
null_gen_gia_nghia = df_gia_nghia[df_gia_nghia['family.hostGender'].isna()]

print(f"Số lượng trùng (Mã hộ & Tên chủ hộ): {len(dup_gia_nghia)}")
print(f"Số lượng thiếu giới tính: {len(null_gen_gia_nghia)}")
if len(null_gen_gia_nghia) > 0:
    display(null_gen_gia_nghia)

--- Thành phố Gia Nghĩa ---
Số lượng trùng mã hộ: 218
Số lượng thiếu giới tính: 1

,date,family.hostName,family.code,family.coDanTocTaiCho,family.hostGender,family.numberOfMembers,quickReview.result,b1Point,b2Point,classify,reviewer
255,NaN,Nguyễn VĂn A,999,NaN,NaN,1,--,NaN,NaN,Hộ nghèo,NaN

## Tính tỷ lệ % và hiển thị các dòng trùng lặp mã hộ (`family.code`)
Phần này tính toán tỷ lệ phần trăm các dòng bị lặp dựa trên mã hộ và hiển thị các dòng đó.

In [21]:
# Huyện Cư Jút
dups = df_cu_jut[df_cu_jut.duplicated(subset=['family.code', 'family.hostName'], keep=False)]
percent = (len(dups) / len(df_cu_jut)) * 100
print(f"Huyện Cư Jút: {percent:.2f}% dòng bị lặp ({len(dups)}/{len(df_cu_jut)})")
display(dups.sort_values(['family.code', 'family.hostName']).head(10))

Huyện Cư Jút: 89.11% dòng bị lặp (1874/2103)

,date,family.hostName,family.code,family.coDanTocTaiCho,family.hostGender,family.numberOfMembers,quickReview.result,b1Point,b2Point,classify,reviewer
756,NaN,H NGHEO KNUL,1,Có,Nam,6,--,NaN,NaN,Hộ cận nghèo,NaN
1898,NaN,H NGHEO KNUL,1,Có,Nam,6,--,NaN,NaN,Hộ cận nghèo,NaN
175,NaN,HOÀNG THỊ TIỆM,1,NaN,Nữ,6,--,NaN,NaN,Hộ nghèo,NaN
1291,NaN,HOÀNG THỊ TIỆM,1,NaN,Nữ,6,--,NaN,NaN,Hộ nghèo,NaN
369,NaN,LƯƠNG VĂN PHONG,1,NaN,Nam,5,--,NaN,NaN,Hộ nghèo,NaN
1476,NaN,LƯƠNG VĂN PHONG,1,NaN,Nam,5,--,NaN,NaN,Hộ nghèo,NaN
134,NaN,LỤC VĂN CƯỜNG,1,NaN,Nam,5,--,NaN,NaN,Hộ nghèo,NaN
1238,NaN,LỤC VĂN CƯỜNG,1,NaN,Nam,5,--,NaN,NaN,Hộ nghèo,NaN
705,NaN,NGUYỄN THỊ TUYẾT,1,NaN,Nữ,2,--,NaN,NaN,Hộ nghèo,NaN
1876,NaN,NGUYỄN THỊ TUYẾT,1,NaN,Nữ,2,--,NaN,NaN,Hộ nghèo,NaN

In [ ]:
# Huyện Krông Nô
dups = df_krong_no[df_krong_no.duplicated(subset=['family.code', 'family.hostName'], keep=False)]
percent = (len(dups) / len(df_krong_no)) * 100
print(f"Huyện Krông Nô: {percent:.2f}% dòng bị lặp ({len(dups)}/{len(df_krong_no)})")
display(dups.sort_values(['family.code', 'family.hostName']).head(10))

Huyện Krông Nô: 98.61% dòng bị lặp (2987/3029)

,date,family.hostName,family.code,family.coDanTocTaiCho,family.hostGender,family.numberOfMembers,quickReview.result,b1Point,b2Point,classify,reviewer
1573,NaN,Lê Văn Vinh,1,NaN,Nam,3,--,NaN,NaN,Hộ nghèo,NaN
2442,NaN,TRIỆU MÙI NHẬY,1,NaN,Nữ,4,--,NaN,NaN,Hộ nghèo,NaN
2174,NaN,Y - Si Bkrông,1,Có,Nam,8,--,NaN,NaN,Hộ nghèo,NaN
2411,NaN,Trần Thị Đào,1,NaN,Nữ,2,--,NaN,NaN,Hộ nghèo,NaN
2709,NaN,Nguyễn Hồng Quảng,1,NaN,Nam,3,--,NaN,NaN,Hộ cận nghèo,NaN
254,NaN,Vi Văn Khăm,1,NaN,Nam,5,--,NaN,NaN,Hộ cận nghèo,NaN
1817,NaN,Vi Văn Khăm,1,NaN,Nam,5,--,NaN,NaN,Hộ cận nghèo,NaN
2683,NaN,HỒ KHA,1,NaN,Nam,4,--,NaN,NaN,Hộ nghèo,NaN
584,NaN,LÊ THỊ OANH,1,NaN,Nữ,5,--,NaN,NaN,Hộ cận nghèo,NaN
2049,NaN,Hoàng Văn Cường,1,NaN,Nam,4,--,NaN,NaN,Hộ cận nghèo,NaN

In [ ]:
# Huyện Tuy Đức
dups = df_tuy_duc[df_tuy_duc.duplicated(subset=['family.code', 'family.hostName'], keep=False)]
percent = (len(dups) / len(df_tuy_duc)) * 100
print(f"Huyện Tuy Đức: {percent:.2f}% dòng bị lặp ({len(dups)}/{len(df_tuy_duc)})")
display(dups.sort_values(['family.code', 'family.hostName']).head(10))

Huyện Tuy Đức: 96.17% dòng bị lặp (5066/5268)

,date,family.hostName,family.code,family.coDanTocTaiCho,family.hostGender,family.numberOfMembers,quickReview.result,b1Point,b2Point,classify,reviewer
3725,NaN,HỒ THỊ XUÂN,1,NaN,Nữ,1,--,NaN,NaN,Hộ nghèo,NaN
418,NaN,THỊ DJAO,1,Có,Nam,6,--,NaN,NaN,Hộ cận nghèo,NaN
1344,NaN,NGUYỄN BÁ HY,1,NaN,Nam,5,--,NaN,NaN,Hộ cận nghèo,NaN
4112,NaN,LÊ VIẾT HƯNG,1,NaN,Nam,5,--,NaN,NaN,Hộ cận nghèo,NaN
1432,NaN,ĐIỂU NHRƠM,1,Có,Nam,8,--,NaN,NaN,Hộ cận nghèo,NaN
173,NaN,LÊ VIẾT HƯNG,1,NaN,Nam,5,--,NaN,NaN,Hộ cận nghèo,NaN
2187,NaN,ĐIỂU NHRƠM,1,Có,Nam,8,--,NaN,NaN,Hộ cận nghèo,NaN
2026,NaN,NGUYỄN BÁ HY,1,NaN,Nam,5,--,NaN,NaN,Hộ cận nghèo,NaN
1965,NaN,NGUYỄN VẠN ĐÌNH,1,NaN,Nam,5,--,NaN,NaN,Hộ nghèo,NaN
833,NaN,ĐIỂU NHRƠM,1,Có,Nam,8,--,NaN,NaN,Hộ cận nghèo,NaN

In [ ]:
# Huyện Đăk Glong
dups = df_dak_glong[df_dak_glong.duplicated(subset=['family.code', 'family.hostName'], keep=False)]
percent = (len(dups) / len(df_dak_glong)) * 100
print(f"Huyện Đăk Glong: {percent:.2f}% dòng bị lặp ({len(dups)}/{len(df_dak_glong)})")
display(dups.sort_values(['family.code', 'family.hostName']).head(10))

Huyện Đăk Glong: 96.38% dòng bị lặp (4555/4726)

,date,family.hostName,family.code,family.coDanTocTaiCho,family.hostGender,family.numberOfMembers,quickReview.result,b1Point,b2Point,classify,reviewer
1694,NaN,LƯƠNG THỊ VÂN,1,NaN,Nữ,5,--,NaN,NaN,Hộ cận nghèo,NaN
514,NaN,H' DUYÊN,1,Có,Nữ,4,--,NaN,NaN,Hộ cận nghèo,NaN
4228,NaN,K' TANG,1,Có,Nam,4,--,NaN,NaN,Hộ nghèo,NaN
3016,NaN,K' ĐIỆP,1,Có,Nam,3,--,NaN,NaN,Hộ nghèo,NaN
4099,NaN,K' Linh,1,Có,Nam,4,--,NaN,NaN,Hộ cận nghèo,NaN
158,NaN,Ngô Xuân Thái,1,NaN,Nam,6,--,NaN,NaN,Hộ cận nghèo,NaN
3614,NaN,K' Linh,1,Có,Nam,4,--,NaN,NaN,Hộ cận nghèo,NaN
1641,NaN,HUỲNH THANH TÙNG,1,NaN,Nam,7,--,NaN,NaN,Hộ cận nghèo,NaN
2962,NaN,LÂM THỊ THU NGUYỆT,1,NaN,Nữ,3,--,NaN,NaN,Hộ cận nghèo,NaN
3455,NaN,TRẦN VĂN HUỲNH,1,NaN,Nam,6,--,NaN,NaN,Hộ cận nghèo,NaN

In [ ]:
# Huyện Đắk Mil
dups = df_dak_mil[df_dak_mil.duplicated(subset=['family.code', 'family.hostName'], keep=False)]
percent = (len(dups) / len(df_dak_mil)) * 100
print(f"Huyện Đắk Mil: {percent:.2f}% dòng bị lặp ({len(dups)}/{len(df_dak_mil)})")
display(dups.sort_values(['family.code', 'family.hostName']).head(10))

Huyện Đắk Mil: 99.93% dòng bị lặp (1412/1413)

,date,family.hostName,family.code,family.coDanTocTaiCho,family.hostGender,family.numberOfMembers,quickReview.result,b1Point,b2Point,classify,reviewer
1,NaN,NGUYỄN THỊ TAM,1,NaN,Nữ,2,--,NaN,NaN,Hộ nghèo,NaN
642,NaN,NGUYỄN THỊ LAN,1,NaN,Nữ,5,--,NaN,NaN,Hộ cận nghèo,NaN
704,NaN,Nguyễn Thị Tứ,1,NaN,Nữ,3,--,NaN,NaN,Hộ cận nghèo,NaN
739,NaN,Triệu Văn Huế,1,NaN,Nam,5,--,NaN,NaN,Hộ nghèo,NaN
740,NaN,Võ Văn Bảy,1,NaN,Nam,3,--,NaN,NaN,Hộ cận nghèo,NaN
486,NaN,NGUYỄN HOÀNG KHÁNH BĂNG,1,NaN,Nữ,6,--,NaN,NaN,Hộ cận nghèo,NaN
470,NaN,HUỲNH XUÂN THÀNH,1,NaN,Nam,5,--,NaN,NaN,Hộ cận nghèo,NaN
949,NaN,Nguyễn Thị Cẩm Hồng,1,NaN,Nữ,4,--,NaN,NaN,Hộ cận nghèo,NaN
1102,NaN,LÊ THỊ LINH,1,NaN,Nữ,2,--,NaN,NaN,Hộ nghèo,NaN
1115,NaN,NGUYỄN THỊ LAN,1,NaN,Nữ,5,--,NaN,NaN,Hộ cận nghèo,NaN

In [ ]:
# Huyện Đắk RLấp
dups = df_dak_rlap[df_dak_rlap.duplicated(subset=['family.code', 'family.hostName'], keep=False)]
percent = (len(dups) / len(df_dak_rlap)) * 100
print(f"Huyện Đắk RLấp: {percent:.2f}% dòng bị lặp ({len(dups)}/{len(df_dak_rlap)})")
display(dups.sort_values(['family.code', 'family.hostName']).head(10))

Huyện Đắk RLấp: 98.15% dòng bị lặp (1170/1192)

,date,family.hostName,family.code,family.coDanTocTaiCho,family.hostGender,family.numberOfMembers,quickReview.result,b1Point,b2Point,classify,reviewer
18,NaN,Bùi Văn Tý,1,NaN,Nam,4,--,NaN,NaN,Hộ nghèo,NaN
999,NaN,Huỳnh Ngọc Hải,1,NaN,Nam,3,--,NaN,NaN,Hộ cận nghèo,NaN
1171,NaN,Điểu Quốc,1,NaN,Nam,6,--,NaN,NaN,Hộ cận nghèo,NaN
152,NaN,VÕ THỊ LÝ,1,NaN,Nữ,1,--,NaN,NaN,Hộ nghèo,NaN
810,NaN,Lý Thị Thúy,1,NaN,Nữ,2,--,NaN,NaN,Hộ cận nghèo,NaN
351,NaN,Liêu Minh Hùng,1,NaN,Nữ,7,--,NaN,NaN,Hộ nghèo,NaN
280,NaN,Lý Thị Dung,1,NaN,Nữ,5,--,NaN,NaN,Hộ nghèo,NaN
230,NaN,Phan Thị Nản,1,NaN,Nữ,3,--,NaN,NaN,Hộ nghèo,NaN
607,NaN,Nguyễn Thắng Bé,1,NaN,Nam,3,--,NaN,NaN,Hộ cận nghèo,NaN
1133,NaN,Trần Thị Hoa,1,NaN,Nữ,3,--,NaN,NaN,Hộ cận nghèo,NaN

In [ ]:
# Huyện Đắk Song
dups = df_dak_song[df_dak_song.duplicated(subset=['family.code', 'family.hostName'], keep=False)]
percent = (len(dups) / len(df_dak_song)) * 100
print(f"Huyện Đắk Song: {percent:.2f}% dòng bị lặp ({len(dups)}/{len(df_dak_song)})")
display(dups.sort_values(['family.code', 'family.hostName']).head(10))

Huyện Đắk Song: 98.69% dòng bị lặp (1807/1831)

,date,family.hostName,family.code,family.coDanTocTaiCho,family.hostGender,family.numberOfMembers,quickReview.result,b1Point,b2Point,classify,reviewer
254,NaN,LÊ THỊ CẨM,1,NaN,Nữ,4,--,NaN,NaN,Hộ nghèo,NaN
106,NaN,Điểu N'Groih,1,Có,Nam,5,--,NaN,NaN,Hộ nghèo,NaN
1304,NaN,Tống Huy Bê,1,NaN,Nam,4,--,NaN,NaN,Hộ cận nghèo,NaN
139,NaN,HOÀNG THỊ TỊNH,1,NaN,Nữ,1,--,NaN,NaN,Hộ nghèo,NaN
186,NaN,Hoàng Cao Khiển,1,NaN,Nam,1,--,NaN,NaN,Hộ nghèo,NaN
1184,NaN,Điểu Toan,1,Có,Nam,5,--,NaN,NaN,Hộ cận nghèo,NaN
202,NaN,Đỗ Thị Thi,1,NaN,Nữ,1,--,NaN,NaN,Hộ nghèo,NaN
1078,NaN,Trương Bá Thọ,1,NaN,Nam,4,--,NaN,NaN,Hộ cận nghèo,NaN
1067,NaN,LÊ THỊ CẨM,1,NaN,Nữ,4,--,NaN,NaN,Hộ nghèo,NaN
1029,NaN,HOÀNG THỊ TỊNH,1,NaN,Nữ,1,--,NaN,NaN,Hộ nghèo,NaN

In [22]:
# Thành phố Gia Nghĩa
dups = df_gia_nghia[df_gia_nghia.duplicated(subset=['family.code', 'family.hostName'], keep=False)]
percent = (len(dups) / len(df_gia_nghia)) * 100
print(f"Thành phố Gia Nghĩa: {percent:.2f}% dòng bị lặp ({len(dups)}/{len(df_gia_nghia)})")
display(dups.sort_values(['family.code', 'family.hostName']).head(10))

Thành phố Gia Nghĩa: 0.00% dòng bị lặp (0/256)

Empty DataFrame
Columns: [date, family.hostName, family.code, family.coDanTocTaiCho, family.hostGender, family.numberOfMembers, quickReview.result, b1Point, b2Point, classify, reviewer]
Index: []